import { useState, useMemo } from 'react';
import Icon from '../components/ui/Icon';
import { BarChart, ChartCard, LineChart } from '../components/charts';
import Button from '../components/ui/Button';
import { ErrorState, LoadingState } from '../components/ui/LoadState';
import PageHeader from '../components/ui/PageHeader';
import StatCard from '../components/ui/StatCard';
import { useBusinessData } from '../api/resources';
import { currency, date, indexById, lastMonthsSeries, number, status } from '../utils/formatters';

const REPORT_TYPES = [
  { key: 'Sales Report',     icon: 'sales'     },
  { key: 'Revenue Report',   icon: 'revenue'   },
  { key: 'Expense Report',   icon: 'expenses'  },
  { key: 'Inventory Report', icon: 'inventory' },
  { key: 'Customer Report',  icon: 'customers' },
];

/** Build a simple print window from an HTML string */
function openPrintWindow(html) {
  const win = window.open('', '_blank', 'width=900,height=700');
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

/** Shared print-page wrapper */
function printTemplate(title, bodyHtml) {
  return `<!DOCTYPE html><html>
  <head>
    <title>${title}</title>
    <style>
      body { font-family: Inter, system-ui, sans-serif; color: #111; padding: 40px; font-size: 14px; }
      h1   { font-size: 22px; margin: 0 0 4px; }
      .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
      th { text-align: left; padding: 8px 10px; font-size: 11px; color: #888;
           text-transform: uppercase; border-bottom: 2px solid #eee; }
      td { padding: 8px 10px; border-bottom: 1px solid #f0f0f0; }
      .footer { margin-top: 32px; font-size: 12px; color: #aaa; text-align: center; }
    </style>
  </head>
  <body>
    <h1>${title}</h1>
    <div class="meta">Generated by SmartBiz &bull; ${new Date().toLocaleDateString()}</div>
    ${bodyHtml}
    <div class="footer">SmartBiz &bull; ${new Date().toLocaleDateString()}</div>
  </body></html>`;
}

export default function Reports() {
  const { data, loading, error, reload } = useBusinessData();
  const [selectedReport, setSelectedReport] = useState('Sales Report');
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');

  // ── All hooks BEFORE any early returns ───────────────────────────────────

  const filteredSales = useMemo(() => {
    if (!data?.sales) return [];
    return data.sales.filter((sale) => {
      const d = new Date(sale.saleDate);
      if (fromDate && d < new Date(fromDate)) return false;
      if (toDate   && d > new Date(toDate))   return false;
      return true;
    });
  }, [data?.sales, fromDate, toDate]);

  const filteredExpenses = useMemo(() => {
    if (!data?.expenses) return [];
    return data.expenses.filter((exp) => {
      const d = new Date(exp.expenseDate);
      if (fromDate && d < new Date(fromDate)) return false;
      if (toDate   && d > new Date(toDate))   return false;
      return true;
    });
  }, [data?.expenses, fromDate, toDate]);

  const revenue  = useMemo(() => lastMonthsSeries(filteredSales,    'saleDate',    'totalAmount'), [filteredSales]);
  const expenses = useMemo(() => lastMonthsSeries(filteredExpenses, 'expenseDate', 'amount'),      [filteredExpenses]);

  const totalSales    = useMemo(() => filteredSales.reduce((s, x)    => s + Number(x.totalAmount || 0), 0), [filteredSales]);
  const totalExpenses = useMemo(() => filteredExpenses.reduce((s, x) => s + Number(x.amount || 0), 0),     [filteredExpenses]);
  const profit        = totalSales - totalExpenses;
  const totalProducts = data?.products?.length || 0;

  const pendingInvoices = useMemo(() => data?.invoices?.filter(i => i.status === 'PENDING').length || 0, [data?.invoices]);
  const paidInvoices    = useMemo(() => data?.invoices?.filter(i => i.status === 'PAID').length    || 0, [data?.invoices]);
  const customerById    = useMemo(() => indexById(data?.customers || []), [data?.customers]);

  // ── Early returns AFTER all hooks ─────────────────────────────────────────
  if (loading) return <LoadingState message="Loading reports..." />;
  if (error)   return <ErrorState  message={error} onRetry={reload} />;

  // ── Print helpers ─────────────────────────────────────────────────────────

  const handlePrintSales = () => {
    const rows = filteredSales.map(s => {
      const custName = customerById[s.customerId]?.fullName || `Customer #${s.customerId || '-'}`;
      return `
      <tr>
        <td>#${s.saleId ?? s.id ?? '—'}</td>
        <td>${custName}</td>
        <td>${date(s.saleDate)}</td>
        <td>${status(s.paymentMethod ?? '')}</td>
        <td>${status(s.status ?? '')}</td>
        <td style="text-align:right">${currency(s.totalAmount)}</td>
      </tr>`;
    }).join('');
    openPrintWindow(printTemplate('Sales Report', `
      <table>
        <thead><tr>
          <th style="width: 12%">Sale ID</th>
          <th style="width: 20%">Customer</th>
          <th style="width: 18%">Date</th>
          <th style="width: 18%">Payment</th>
          <th style="width: 15%">Status</th>
          <th style="width: 17%; text-align: right">Total</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="6">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintExpenses = () => {
    const rows = filteredExpenses.map(e => `
      <tr>
        <td>${e.notes ?? '—'}</td>
        <td>${e.category ?? '—'}</td>
        <td>${date(e.expenseDate)}</td>
        <td style="text-align:right">${currency(e.amount)}</td>
      </tr>`).join('');
    openPrintWindow(printTemplate('Expense Report', `
      <table>
        <thead><tr>
          <th style="width: 40%">Description</th>
          <th style="width: 20%">Category</th>
          <th style="width: 20%">Date</th>
          <th style="width: 20%; text-align: right">Amount</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="4">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintInventory = () => {
    const rows = (data.products || []).map(p => {
      const qty = Number(p.stockQuantity || 0);
      const stockLabel = qty <= 0 ? 'Out of Stock' : qty <= 10 ? 'Low Stock' : 'In Stock';
      return `
      <tr>
        <td>${p.productName ?? '—'}</td>
        <td>${p.category ?? '—'}</td>
        <td style="text-align:right">${number(p.stockQuantity)}</td>
        <td style="text-align:right">${currency(p.unitPrice ?? 0)}</td>
        <td>${stockLabel}</td>
      </tr>`;
    }).join('');
    openPrintWindow(printTemplate('Inventory Report', `
      <table>
        <thead><tr>
          <th style="width: 35%">Product</th>
          <th style="width: 20%">Category</th>
          <th style="width: 15%; text-align: right">Stock Qty</th>
          <th style="width: 15%; text-align: right">Price</th>
          <th style="width: 15%">Status</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="5">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintCustomers = () => {
    const rows = (data.customers || []).map(c => `
      <tr>
        <td>${c.fullName ?? '—'}</td>
        <td>${c.email ?? '—'}</td>
        <td>${c.phone ?? '—'}</td>
        <td>${c.address ?? '—'}</td>
      </tr>`).join('');
    openPrintWindow(printTemplate('Customer Report', `
      <table>
        <thead><tr>
          <th style="width: 25%">Name</th>
          <th style="width: 25%">Email</th>
          <th style="width: 20%">Phone</th>
          <th style="width: 30%">Address</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="4">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintRevenue = () => {
    openPrintWindow(printTemplate('Revenue Report', `
      <table>
        <thead><tr>
          <th style="width: 40%">Period</th>
          <th style="width: 20%; text-align: right">Total Sales</th>
          <th style="width: 20%; text-align: right">Total Expenses</th>
          <th style="width: 20%; text-align: right">Profit</th>
        </tr></thead>
        <tbody>
          <tr>
            <td>${fromDate || 'All time'} – ${toDate || 'Now'}</td>
            <td style="text-align:right">${currency(totalSales)}</td>
            <td style="text-align:right">${currency(totalExpenses)}</td>
            <td style="text-align:right;font-weight:700;color:${profit >= 0 ? 'green' : 'red'}">${currency(profit)}</td>
          </tr>
        </tbody>
      </table>`));
  };

  const printHandlers = {
    'Sales Report':     handlePrintSales,
    'Revenue Report':   handlePrintRevenue,
    'Expense Report':   handlePrintExpenses,
    'Inventory Report': handlePrintInventory,
    'Customer Report':  handlePrintCustomers,
  };

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="page">
      <PageHeader
        eyebrow="Reports"
        title="Reporting Dashboard"
        description="Generate and print reports from live SmartBiz records."
        actions={(
          <Button variant="primary" onClick={printHandlers[selectedReport]}>
            <Icon name="print" size={17} style={{ marginRight: 6 }} /> Print {selectedReport}
          </Button>
        )}
      />

      {/* Report Type Selector */}
      <section className="report-type-grid">
        {REPORT_TYPES.map(({ key, icon }) => (
          <button
            key={key}
            type="button"
            onClick={() => setSelectedReport(key)}
            style={selectedReport === key ? {
              background: 'var(--blue-soft)',
              color: 'var(--blue)',
              borderColor: 'var(--blue)',
            } : {}}
          >
            <span style={{ fontSize: '22px', display: 'flex', justifyContent: 'center', marginBottom: '6px' }}>
              <Icon name={icon} size={24} />
            </span>
            {key}
          </button>
        ))}
      </section>

      {/* Date range filter */}
      <div className="report-toolbar">
        <label>
          From
          <input
            type="date"
            value={fromDate}
            onChange={(e) => setFromDate(e.target.value)}
          />
        </label>
        <label>
          To
          <input
            type="date"
            value={toDate}
            onChange={(e) => setToDate(e.target.value)}
          />
        </label>
        {(fromDate || toDate) && (
          <button
            type="button"
            className="app-button ghost"
            onClick={() => { setFromDate(''); setToDate(''); }}
          >
            <Icon name="close" size={15} /> Clear filter
          </button>
        )}
      </div>

      {/* ── SALES REPORT ─────────────────────────────────────────────── */}
      {selectedReport === 'Sales Report' && (
        <>
          <section className="summary-grid">
            <StatCard label="Total Sales" value={currency(totalSales)} growth="Live" icon="revenue" />
            <StatCard label="Transactions" value={number(filteredSales.length)} growth="Live" icon="revenue" />
            <StatCard
              label="Avg. Sale Value"
              value={currency(filteredSales.length ? totalSales / filteredSales.length : 0)}
              growth="Live"
              icon="revenue"
            />
          </section>

          <section className="dashboard-grid two">
            <ChartCard title="Sales Over Time" subtitle="Monthly totals">
              <LineChart data={revenue.values} labels={revenue.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Comparison by month">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="card">
            <h3 style={{ margin: '0 0 16px', fontSize: '16px' }}>Sales Transactions</h3>
            {filteredSales.length ? (
              <div className="table-wrap">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th style={{ width: '12%' }}>Sale ID</th>
                      <th style={{ width: '20%' }}>Customer</th>
                      <th style={{ width: '18%' }}>Date</th>
                      <th style={{ width: '18%' }}>Payment Method</th>
                      <th style={{ width: '15%' }}>Status</th>
                      <th style={{ width: '17%', textAlign: 'right' }}>Total Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredSales.map((sale) => {
                      const custName = customerById[sale.customerId]?.fullName || `Customer #${sale.customerId || '-'}`;
                      return (
                        <tr key={sale.id ?? sale.saleId}>
                          <td>#{sale.saleId ?? sale.id}</td>
                          <td style={{ fontWeight: 500 }}>{custName}</td>
                          <td>{date(sale.saleDate)}</td>
                          <td>{status(sale.paymentMethod ?? '')}</td>
                          <td>
                            <span className={`status-badge ${sale.status?.toLowerCase() || ''}`}>
                              {status(sale.status ?? '')}
                            </span>
                          </td>
                          <td style={{ textAlign: 'right', fontWeight: 700 }}>{currency(sale.totalAmount)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <p style={{ color: 'var(--muted)', margin: 0 }}>No sales in the selected date range.</p>
            )}
          </section>
        </>
      )}

      {/* ── REVENUE REPORT ───────────────────────────────────────────── */}
      {selectedReport === 'Revenue Report' && (
        <>
          <section className="summary-grid">
            <StatCard label="Total Revenue"    value={currency(totalSales)}    growth="Live"       icon="revenue"   />
            <StatCard label="Total Expenses"   value={currency(totalExpenses)} growth="Live"       icon="expenses"  />
            <StatCard label="Net Profit"       value={currency(profit)}        growth={profit >= 0 ? 'Profitable' : 'Loss'} icon="revenue" />
            <StatCard label="Paid Invoices"    value={number(paidInvoices)}    growth="Live"       icon="invoice"   />
            <StatCard label="Pending Invoices" value={number(pendingInvoices)} growth="Live"       icon="invoice"   />
            <StatCard label="Products Listed"  value={number(totalProducts)}   growth="Live"       icon="inventory" />
          </section>

          <section className="dashboard-grid two">
            <ChartCard title="Revenue Trend" subtitle="Monthly sales totals">
              <LineChart data={revenue.values} labels={revenue.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Side-by-side monthly view">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="card">
            <h3 style={{ margin: '0 0 16px', fontSize: '16px' }}>Invoice Summary</h3>
            <div className="table-wrap">
              <table className="data-table">
                <thead>
                  <tr>
                    <th style={{ width: '20%' }}>Invoice No.</th>
                    <th style={{ width: '20%' }}>Issue Date</th>
                    <th style={{ width: '20%' }}>Due Date</th>
                    <th style={{ width: '20%' }}>Status</th>
                    <th style={{ width: '20%', textAlign: 'right' }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {data.invoices?.map((inv) => (
                    <tr key={inv.id}>
                      <td>{inv.invoiceNumber || `INV-${inv.id}`}</td>
                      <td>{date(inv.issueDate)}</td>
                      <td>{date(inv.dueDate)}</td>
                      <td>
                        <span className={`status-badge ${inv.status?.toLowerCase()}`}>
                          {status(inv.status)}
                        </span>
                      </td>
                      <td style={{ textAlign: 'right', fontWeight: 700 }}>{currency(inv.totalAmount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {/* ── EXPENSE REPORT ───────────────────────────────────────────── */}
      {selectedReport === 'Expense Report' && (
        <>
          <section className="summary-grid">
            <StatCard label="Total Expenses"  value={currency(totalExpenses)} growth="Live" icon="expenses" />
            <StatCard label="No. of Expenses" value={number(filteredExpenses.length)} growth="Live" icon="expenses" />
            <StatCard
              label="Avg. Expense"
              value={currency(filteredExpenses.length ? totalExpenses / filteredExpenses.length : 0)}
              growth="Live"
              icon="expenses"
            />
          </section>

          <section className="dashboard-grid two">
            <ChartCard title="Expenses Over Time" subtitle="Monthly totals">
              <LineChart data={expenses.values} labels={expenses.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Comparison">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="card">
            <h3 style={{ margin: '0 0 16px', fontSize: '16px' }}>Expense Records</h3>
            {filteredExpenses.length ? (
              <div className="table-wrap">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th style={{ width: '40%' }}>Description</th>
                      <th style={{ width: '20%' }}>Category</th>
                      <th style={{ width: '20%' }}>Date</th>
                      <th style={{ width: '20%', textAlign: 'right' }}>Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredExpenses.map((exp) => (
                      <tr key={exp.id}>
                        <td>{exp.notes ?? '—'}</td>
                        <td>{exp.category ?? '—'}</td>
                        <td>{date(exp.expenseDate)}</td>
                        <td style={{ textAlign: 'right', fontWeight: 700 }}>{currency(exp.amount)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p style={{ color: 'var(--muted)', margin: 0 }}>No expenses in the selected date range.</p>
            )}
          </section>
        </>
      )}

      {/* ── INVENTORY REPORT ─────────────────────────────────────────── */}
      {selectedReport === 'Inventory Report' && (
        <>
          <section className="summary-grid">
            <StatCard label="Total Products"  value={number(totalProducts)} growth="Live" icon="inventory" />
            <StatCard
              label="Low Stock Items"
              value={number(data.products?.filter(p => Number(p.stockQuantity) > 0 && Number(p.stockQuantity) <= 10).length || 0)}
              growth="Watch"
              icon="inventory"
            />
            <StatCard
              label="Out of Stock"
              value={number(data.products?.filter(p => Number(p.stockQuantity) <= 0).length || 0)}
              growth="Alert"
              icon="inventory"
            />
          </section>

          <section className="card">
            <h3 style={{ margin: '0 0 16px', fontSize: '16px' }}>Inventory Status</h3>
            <div className="table-wrap">
              <table className="data-table">
                <thead>
                  <tr>
                    <th style={{ width: '25%' }}>Product Name</th>
                    <th style={{ width: '15%' }}>Category</th>
                    <th style={{ width: '20%', textAlign: 'right' }}>Stock Qty</th>
                    <th style={{ width: '20%', textAlign: 'right' }}>Selling Price</th>
                    <th style={{ width: '20%' }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {data.products?.map((product) => {
                    const qty = Number(product.stockQuantity || 0);
                    const stockStatus = qty <= 0 ? 'out-of-stock' : qty <= 10 ? 'low-stock' : 'in-stock';
                    const stockLabel  = qty <= 0 ? 'Out of Stock' : qty <= 10 ? 'Low Stock'  : 'In Stock';
                    return (
                      <tr key={product.id}>
                        <td style={{ fontWeight: 500 }}>{product.productName}</td>
                        <td>{product.category ?? '—'}</td>
                        <td style={{ textAlign: 'right' }}>{number(qty)}</td>
                        <td style={{ textAlign: 'right' }}>{currency(product.unitPrice ?? 0)}</td>
                        <td><span className={`status-badge ${stockStatus}`}>{stockLabel}</span></td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {/* ── CUSTOMER REPORT ──────────────────────────────────────────── */}
      {selectedReport === 'Customer Report' && (
        <>
          <section className="summary-grid">
            <StatCard label="Total Customers" value={number(data.customers?.length || 0)} growth="Live" icon="revenue" />
            <StatCard label="Paid Invoices"   value={number(paidInvoices)}               growth="Live" icon="invoice" />
            <StatCard label="Total Revenue"   value={currency(totalSales)}               growth="Live" icon="revenue" />
          </section>

          <section className="card">
            <h3 style={{ margin: '0 0 16px', fontSize: '16px' }}>Customer Directory</h3>
            <div className="table-wrap">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                  </tr>
                </thead>
                <tbody>
                  {data.customers?.map((customer) => (
                    <tr key={customer.id}>
                      <td style={{ fontWeight: 500 }}>{customer.fullName ?? '—'}</td>
                      <td>{customer.email ?? '—'}</td>
                      <td>{customer.phone ?? '—'}</td>
                      <td style={{ color: 'var(--muted)' }}>{customer.address ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}
    </div>
  );
}
